<a href="https://colab.research.google.com/github/sojuvarghese22/ML-Basics-Definations/blob/main/kfoldprogram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [4]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_train,y_train)

In [5]:
digits = load_digits()


In [6]:
from sklearn.model_selection import train_test_split


In [30]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target)

In [8]:

model = SVC()
get_score(model,x_train,x_test,y_train,y_test)


0.9970304380103935

In [32]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)



In [33]:
svm_list = []
logistic_list = []
RandomForestClassifier_list = []

for train_index, test_index  in folds.split(digits.data,digits.target):

  train_x, test_x, train_y, train_y = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  model = SVC()
  svm_list.append(get_score(model,x_train,x_test,y_train,y_test))
  
  model1 = LogisticRegression()
  logistic_list.append(get_score(model1,x_train,x_test,y_train,y_test))
  
  model2 = RandomForestClassifier()
  
  RandomForestClassifier_list.append(get_score(model2,x_train,x_test,y_train,y_test))




/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [29]:
print(svm_list)
print(logistic_list)
print(RandomForestClassifier_list)


[0.9948032665181886, 0.9948032665181886, 0.9948032665181886]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]


In [38]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(),digits.data,digits.target)


array([0.92777778, 0.89166667, 0.96100279, 0.97214485, 0.91922006])

In [40]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])